name = "LSQR"
author = "Jacob Williams"
copyright  = "Copyright (c) 2019-2021, Jacob Williams"
license = "BSD-3"
description = "Modern Fortran sparse linear systems solver"
homepage = "https://github.com/jacobwilliams/LSQR"
keywords = ["conjugate-gradient", "sparse", "linear systems", "least-squares"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[library]
source-dir = "src"

[install]
library = true